<?php declare(strict_types=1);

/**
 * @author      Henk Valk (henk@falconmedia.nl)
 * @author      Ruud van Zuidam (allrude@gmail.com)
 * @package     Belco_Hyva
 * @since       version 0.4.1
 * @copyright   2024 Falcon Media. All rights reserved.
 * https://www.falconmedia.nl
 */

use Belco\Hyva\ViewModel\BelcoConfig;
use Hyva\Theme\Model\ViewModelRegistry;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var ViewModelRegistry $viewModels */
/** @var Escaper $escaper */
/** @var Template $block */

/** @var BelcoConfig $belcoConfig */
$belcoConfig = $viewModels->require(BelcoConfig::class);

?>

<script>
    window.belcoConfig = <?= json_encode($belcoConfig->getSectionData()) ?>;
    window.addEventListener('init-external-scripts', () => {
        !function(n,o){var e=window.belcoFunction||"Belco";window[e]||(window[e]=function(n){if(void 0===window[e][n])throw new Error("Unknown method");return window[e][n].apply(window[e],Array.prototype.slice.call(arguments,1))}),window[e]._q=[];for(var i=["init","sync","track","page","open","close","toggle","on","once","off","anonymousId","customer","reset","sendMessage"],t=function(n){return function(){var o=Array.prototype.slice.call(arguments);return o.unshift(n),window[e]._q.push(o),window[e]}},w=0;w<i.length;w++){var r=i[w];window[e][r]=t(r)}window[e].load=function(e){if(!n.getElementById("belco-js")){var i=n.createElement(o);i.async=!0,i.id="belco-js",i.type="text/javascript",i.src="//cdn.belco.io/v2/widget.js",i.onload=function(n){"function"==typeof e&&e(n)};var t=n.getElementsByTagName(o)[0];t.parentNode.insertBefore(i,t)}},window.belcoConfig&&window[e].load(function(){window[e]("init",window.belcoConfig)})}(document,"script");
    }, {once: true, passive: true});
</script>
